### ISSUE TITLE
Current version is broken

### ISSUE THREAD

**Issue by marcospassos** [krenor/prometheus-client#1]
I'm trying to run the example shown in the readme but the latest version seems broken:

```php
TypeError : Argument 2 passed to Krenor\Prometheus\Sample::__construct() must be of the type float, string given, called in 
```

Stacktrace:
```php
Contracts/SamplesBuilder.php on line 43
Sample.php:31
Contracts/SamplesBuilder.php:43
Collect/Support/Collection.php:638
Contracts/SamplesBuilder.php:45
Storage/StorageManager.php:91
CollectorRegistry.php:55
Collect/Support/Collection.php:638
CollectorRegistry.php:56
```

**Comment by krenor** [comment]
Are you using the `0.4` version or the latest `develop` Branch?
And do you have `declare(strict_types=1)` in the file you're testing from?

Just spun up a docker container on `0.4` and `develop` which both work as expected.

```
# HELP example_multi_labeled_counter Example Counter using multiple labels.
# TYPE example_multi_labeled_counter counter
example_multi_labeled_counter{example_label="foo",other_label="bar",yet_another_label="baz"} 3
example_multi_labeled_counter{example_label="some",other_label="label",yet_another_label="values"} 1
```

**Comment by marcospassos** [comment]
I'm using the latest composer released version. And yes, we use strict types everywhere.

**Comment by marcospassos** [comment]
But still, debugging the code, the library is passing a string (in fact, the repository key) as the metric value, which looks to be quite weird.

**Comment by krenor** [comment]
Weird, I can't really reproduce the error. Can you send me your sample code?
